title: S.Yabunaka[strCode] Blog.
description: S.Yabunaka [strCode] blog.
author: S.Yabunaka [strCode]
url: https://strcode-yabu.github.io/blog/
repository: /blog
since: 2021
excerpt_separator: <!--more-->
theme: jekyll-theme-hacker