title: S.Yabunaka[strCode] Blog.
description: S.Yabunaka [strCode] blog.
author: S.Yabunaka [strCode]
url: https://strcode-yabu.github.io/blog
repository: /blog
since: 2021
google_analytics: G-2QFR6LXEZM
excerpt_separator: <!--more-->
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: table
theme: jekyll-theme-hacker